dist: trusty

sudo: required

language: go

go:
  - "1.18.x"

env:
  - TARGET=testversion5.6
  - TARGET=testversion5.7
  - TARGET=testversion8.0
  - TARGET=testpercona5.7
  - TARGET=testpercona8.0
  - TARGET=testmariadb10.3
  - TARGET=testmariadb10.8
  - TARGET=testtidb6.1.0

services:
  - docker

script:
  - test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
  - make test
  - make vet
  - make "${TARGET}"

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
